version: '3.2'
services:
  database:
    image: postgres:15.4
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

volumes:
  database-data: # named volumes can be managed easier using docker-compose